name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: set up JDK 21 # এখানে ১৭ থেকে বাড়িয়ে ২১ করা হলো
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          
      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/android
          
      - name: Build Web App
        run: npm run build
        
      - name: Create and Sync Android Platform
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android
        
      - name: Build APK with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Awaj-App-Debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
